create sequence tb_budget_product_seq start with 1 increment by 50;
create sequence tb_budget_seq start with 1 increment by 50;
create sequence tb_client_seq start with 1 increment by 50;
create table tb_brand_car (id bigserial not null, name varchar(255), primary key (id));
create table tb_budget (id bigint not null, entry_date timestamp(6), milage_vehicle float(53), observation varchar(255), status smallint, client_id bigint, vehicle_id bigint, primary key (id));
create table tb_budget_product (id bigint not null, brand varchar(255), price float(53), quantity integer, budget_id bigint, product_id bigint, primary key (id));
create table tb_client (id bigint not null, address varchar(255), city_state varchar(255), complement_address varchar(255), date_birth date, email varchar(255), name varchar(50), phone varchar(255), zip_code varchar(255), primary key (id));
create table tb_model_car (id bigserial not null, name varchar(255), brand_car_id bigint, primary key (id));
create table tb_product (id bigserial not null, name varchar(255), price float(53), primary key (id));
create table tb_vehicle (id bigserial not null, car_model_data integer, color varchar(255), license_plate varchar(255), milage float(53), client_id bigint, model_car_id bigint, primary key (id));
alter table if exists tb_budget add constraint FKg4dm2ksjxipgsh9feb356r2vs foreign key (client_id) references tb_client;
alter table if exists tb_budget add constraint FKl1jf7dj35gpri4byrhlr8reuj foreign key (vehicle_id) references tb_vehicle;
alter table if exists tb_budget_product add constraint FK6cugse6nya5og7oe00n5rl04 foreign key (budget_id) references tb_budget;
alter table if exists tb_budget_product add constraint FKdxafxq1mvnd0eaa2pbmw0hxpx foreign key (product_id) references tb_product;
alter table if exists tb_model_car add constraint FKqdgfory4lj7twc5kwywbfpglb foreign key (brand_car_id) references tb_brand_car;
alter table if exists tb_vehicle add constraint FKf2dkw20xquaxmh50sjcyqwmmb foreign key (client_id) references tb_client;
alter table if exists tb_vehicle add constraint FK4rq8cp6r6imw789v0rjpnx4o8 foreign key (model_car_id) references tb_model_car;
